### ISSUE TITLE
Problem installing with spack when ROCBLAS buildable is False

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos-kernels#2349]
I am trying to install Kokkos-Kernels 4.4.01 using spack and I want Kokkos-Kernels to use the version of ROCBLAS that's already installed on the machine. In my `packages.yml`, I have:
```
packages: 
  hip:
    externals:
      - spec: "hip@6.0.0 arch=linux-sles15-zen" 
        prefix: /opt/rocm-6.0.0
    buildable: False
  hsa-rocr-dev:
    externals: 
      - spec: "hsa-rocr-dev@6.0.0 arch=linux-sles15-zen"
        prefix: /opt/rocm-6.0.0
    buildable: False
  llvm-amdgpu:
    externals:
      - spec: "llvm-amdgpu@6.0.0 arch=linux-sles15-zen"
        prefix: /opt/rocm-6.0.0/llvm
    buildable: False
  rocblas:
    externals:
      - spec: "rocblas@6.0.0 arch=linux-sles15-zen"
        prefix: /opt/rocm-6.0.0
    buildable: False
```
I use the following command:
```
spack install --reuse kokkos-kernels@4.4.01 +rocblas ^kokkos@4.4.01+rocm amdgpu_target=gfx90a
```
I get the error:
```
     22    -- Found Kokkos version 4.4.1 at /autofs/nccs-svm1_proj/ums018/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/kokkos-4.4.01-63qwbybeixbzvgmnazmfutpeb2rochuv/lib64/cmake/Kokkos
  >> 23    CMake Error at /autofs/nccs-svm1_proj/ums018/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/cmake-3.27.9-svbkijtxp3hdgjsyb6gjsqbgjarnaty2/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     24      Could NOT find TPLROCBLAS (missing: ROCBLAS_INCLUDE_DIRS)
     25    Call Stack (most recent call first):
     26      /autofs/nccs-svm1_proj/ums018/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/cmake-3.27.9-svbkijtxp3hdgjsyb6gjsqbgjarnaty2/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
     27      cmake/kokkoskernels_tpls.cmake:285 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
     28      cmake/Modules/FindTPLROCBLAS.cmake:25 (kokkoskernels_find_imported)
     29      cmake/kokkoskernels_tpls.cmake:383 (FIND_PACKAGE)

```

I don't know how to set `ROCBLAS_INCLUDE_DIRS` when using spack. I have tried to export `ROCBLAS_INCLUDE_DIRS` but spack ignores it. I have also tried to change the path in the `packages.yml` but I get the same error. Any idea how to fix this issue? I **have to** use spack to install Kokkos-Kernels.
