### ISSUE TITLE
ETI System and file structure

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-kernels#31]
Ok I think I am finally close to make this ETI stuff work properly. There is some funky compiler stuff with regards to using extern template instantiations for classes, in particular if you want to allow instantiations of other types but I believe my solution is now fool proof ......

Furthermore I believe the file structure and naming etc needs some cleanup. In particular this focus on MultiVector which historically comes from Tpetra is confusing for standalone users. 

Lets start with some requirements what we need to be able to do::
* pre-compile functions, and prevent them from being implicitly instantiated (ETI)
* Even with ETI on, allow other input types (say for example extended precision, or nonstandard data layouts)
* call TPLs (MKL, CUBLAS etc.) for input types which allow it
* disallow anything other than ETI types if requested
* check what type of instantiation gets hit in apps (ETI, Non-ETI, TPL)

In order to do all this we came up with a design which has  3 functionality layers (I will go into details later):

1. User Interface: void foo(ViewType a, Scalar alpha): takes views accepts all kinds of combinations; calls the specialization layer
2. Specialization Layer: struct Foo { static void foo(ViewInternalType a, Scalar alpha); }; makes sure that only the minimally necessary number of instantiations exists, serves as ETI specialization layer, serves as TPL specialization layer
3. Implementation Layer: This is called by the specialization layer, and has the actual functors etc.

Now I want to go through a couple of design aspects in the next posts.

**Comment by crtrott** [comment]
I thought now long and hard about a sane, sustainable way for organizing this into files. Here is what I came up with:
```
src:
  KokkosBlas.hpp: includes all the KokkosBlas function header files
      KokkosBlas1_foo.hpp (contains user interface functions for foo)
src/impl:
  KokkosBlas1_foo_impl.hpp: The actual implementation of the functions (Functors etc.)
  KokkosBlas1_foo_spec.hpp: The specialization layer
src/impl/tpl
  KokkosBlas1_foo_spec_tpl_avail.hpp: Availability of TPLs for particular types
  KokkosBlas1_foo_spec_tpl_decl.hpp: The Specialization declaration for using tuples
src/impl/generated_specializations_hpp
  KokkosBlas1_foo_spec_avail.hpp: Availability declarations for ETI types
  KokkosBlas1_foo_spec_declhpp: Specialization declarations for ETI types
src/impl/generated_specializations_cpp/foo
  KokkosBlas1_foo_spec_double_LayoutRight_Cuda_CudaSpace.cpp: one instantiation for an extern template
```

Lets talk about what you need to touch to do specific things:

# Add a new function:
* Add all those files based on the template provided later
* Modify the scripts which generate the auto generated files

# Modify the implementation of a function
* Only `src/impl/KokkosBlas1_foo_impl.hpp` needs to be modified

# Add a new ETI type
* modify the scripts which generate the auto generated files

# Add a new TPL variant
* Modify the files in impl/tpl/ to add the new TPL (declare its availability, and provide the implementation of how to call it)
